### ISSUE TITLE
Error in AMP calculation for very long time windows

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#7] opened 2020-04-26 22:03 UTC
I just used the line described below and the error attached appeared, seems to be related to the calculation of tav or amp. @darkquasar 

**python bestiapop.py -a generate-met-file -y "1889-2017" -c "radiation max_temp min_temp daily_rain" -lat "-40.15 -39.55" -lon "143.85 144.15" -o D:\MET**

I think it is associated with the year period. Due to when the period is shorter, the error disappears.

![Untitled](https://user-images.githubusercontent.com/41041705/80321050-76853980-885d-11ea-8a7b-88433cca9045.jpg)

**Comment by darkquasar** [comment] 2020-04-27 03:09
This error might be tricky to catch. The error says `attempt to get argmax of an empty sequence` which would indicate to me that the array we create to obtain the **"maxmaxtbymonth"** variable on line 566 might be empty, but I don't know why...

To troubleshoot you might have to: 
1. Try the script with different year ranges and starting/ending year, we need to understand whether the error is caused by: (a) an excessive range of years (like too many years to process data from), or (b) a particular year or range of years (let's say 2000 to 2002 are causing the issue)
2. Look at lines 564 to 566
3. Potentially copy/paste the whole code of `bestiapop.py` in a Jupyter Notebook cell and execute, this will load the script in memory and you will be able to setup breakpoints in the script to understand where it is failing

**Comment by JJguri** [comment] 2020-04-27 23:17
solved. I found the error in the amp calculation. I changed the formula to calculate amp. The error is fixed and as an example, you can see the product for 91 gridded cells that cover King Island for 128 years downloaded together (\sample_data\MET). The download was done with the following command:

**python bestiapop.py -a generate-met-file -y "1889-2017" -c "radiation max_temp min_temp daily_rain" -lat "-40.15 -39.55" -lon "143.85 144.15" -o D:\MET**

Two issues remain:
- the code is creating METs for empty cells (only the cells that cover land have data). Probably an exemption line needs to be added somewhere to avoid the generation of empty files.
- it took 5 hs 48 min and 40 sec to download this selection of grids. It means an efficiency of 3.8 min/file (128 yr per file). If you want to download the entire agricultural areas in Tasmania at once (1730 grids), it will take 110 hs approx just considering the grids that cover the land.

**Comment by darkquasar** [comment] 2020-04-29 05:03
looks good, I will close this issue now then, can you please raise an issue for the creation of empty MET files? Good work!

**Closed as completed by darkquasar** 2020-04-29 05:03 UTC
